name: Deploy Node.js to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout del código
      uses: actions/checkout@v4

    - name: 2. Configurar SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: 3. Agregar fingerprint del servidor
      run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: 4. Sincronizar archivos al servidor
      run: |
        rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.github' ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/electroschock

    - name: 5. Ejecutar comandos en EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          cd /home/ubuntu/electroschock

          npm install

          # Usar PM2 con el nombre correcto
          pm2 restart index.js --name "electroshok" || pm2 start index.js --name "electroshok" --watch

          # Guardar el estado de PM2
          pm2 save
        EOF